# Generated by Django 3.1.3 on 2021-08-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210804_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
