# Generated by Django 3.1.3 on 2021-08-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210804_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='detalle',
            field=models.ManyToManyField(to='app.Detalles'),
        ),
    ]
