# Generated by Django 3.1.3 on 2021-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210804_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='parcial2',
            field=models.CharField(choices=[('1', 'Dos')], default=1, max_length=1, verbose_name='Parcial'),
        ),
    ]
