# Generated by Django 3.1.3 on 2021-08-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210804_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.programa', verbose_name='Materia'),
            preserve_default=False,
        ),
    ]
