# Generated by Django 3.1.3 on 2021-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cursos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='imagen_curso',
            field=models.ImageField(null=True, upload_to='images/cursos'),
        ),
    ]
