# Generated by Django 3.1.3 on 2021-08-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210809_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='horario_pro',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='imagen_pro',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='nombre_pro',
            new_name='nombre',
        ),
    ]
