# Generated by Django 3.1.3 on 2021-08-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210809_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='horario',
            new_name='horario_pro',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='imagen',
            new_name='imagen_pro',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='nombre',
            new_name='nombre_pro',
        ),
    ]
