# Generated by Django 3.1.3 on 2021-08-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210809_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asis',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de asistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='horario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.horarios', verbose_name='Hora'),
        ),
    ]
