# Generated by Django 3.1.3 on 2021-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210818_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado_asis',
            field=models.BooleanField(blank=True),
        ),
    ]
