# Generated by Django 3.1.3 on 2021-08-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210818_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado_asis',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ManyToManyField(blank=True, null=True, to='app.Estudiante'),
        ),
    ]
