# Generated by Django 3.1.3 on 2021-08-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_matriculaactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaactual',
            name='nivel',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5'), ('6', 'Nivel 6'), ('7', 'Nivel 7')], default=1, max_length=1, verbose_name='Nivel a matricular'),
            preserve_default=False,
        ),
    ]
