# Generated by Django 3.1.3 on 2021-08-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_matriculaactual_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaactual',
            name='curso',
            field=models.ManyToManyField(to='app.Cursos', verbose_name='Seleccione el Curso'),
        ),
        migrations.AddField(
            model_name='matriculaactual',
            name='programa',
            field=models.ManyToManyField(to='app.Programa', verbose_name='Seleccione el Programa'),
        ),
    ]
