# Generated by Django 3.1.3 on 2021-08-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210820_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaactual',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matriculaactual',
            name='programa',
        ),
    ]
