# Generated by Django 3.1.3 on 2021-08-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210820_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='nivel',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
