# Generated by Django 3.1.3 on 2021-08-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_asistencia_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='nivel',
            new_name='niveles',
        ),
    ]
