# Generated by Django 3.1.3 on 2021-08-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210820_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Humano',
            fields=[
                ('imagen_th', models.ImageField(null=True, upload_to='images/talento_humano')),
                ('cedula_th', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombres_th', models.CharField(max_length=25, verbose_name='Nombres')),
                ('apellidos_th', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('Fecha', models.DateField(verbose_name='Fecha de Entrega lista chequeo')),
                ('telefono', models.CharField(max_length=10)),
                ('cargo_th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo', verbose_name='Cargo por el que postula')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direccion', verbose_name='Dirección')),
            ],
        ),
        migrations.DeleteModel(
            name='Talento_Humano',
        ),
    ]
