# Generated by Django 3.1.3 on 2021-08-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210825_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_Humano',
            new_name='Talento_Humano',
        ),
    ]
