# Generated by Django 3.1.3 on 2021-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_talento_humano_hojavida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talento_humano',
            name='hojaVida',
            field=models.FileField(upload_to='file/talento_humano/<pk>/hoja de vida'),
        ),
    ]
