# Generated by Django 3.1.3 on 2021-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210825_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talento_humano',
            name='hojaVida',
            field=models.FileField(upload_to='file/talento_humano/<cedula_th>/hoja de vida'),
        ),
    ]
