# Generated by Django 3.1.3 on 2021-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210825_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talento_humano',
            name='hojaVida',
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='Antecedentes',
            field=models.FileField(default=1, upload_to='file/talento_humano/Antecedentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='CarnetDiscap',
            field=models.FileField(default=1, upload_to='file/talento_humano/Carnet discapacidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='CertiBancaria',
            field=models.FileField(default=1, upload_to='file/talento_humano/Cerficacion Bancaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='CertiImpedimento',
            field=models.FileField(default=1, upload_to='file/talento_humano/Certificacion Impedimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='CopiaCedula',
            field=models.FileField(default=1, upload_to='file/talento_humano/Copia Cedula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='CopiaRuc',
            field=models.FileField(default=1, upload_to='file/talento_humano/Copia del Ruc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='Cursos',
            field=models.FileField(default=1, upload_to='file/talento_humano/Cursos realizados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='Experiencia',
            field=models.FileField(default=1, upload_to='file/talento_humano/experiencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='Historial',
            field=models.FileField(default=1, upload_to='file/talento_humano/Historial Laboral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='HojaVida',
            field=models.FileField(default=1, upload_to='file/talento_humano/hoja de vida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talento_humano',
            name='Titulos',
            field=models.FileField(default=1, upload_to='file/talento_humano/Titulos'),
            preserve_default=False,
        ),
    ]
