# Generated by Django 3.1.3 on 2021-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210825_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='horario',
        ),
        migrations.AddField(
            model_name='niveles',
            name='horario',
            field=models.ManyToManyField(to='app.Horarios'),
        ),
    ]
