# Generated by Django 3.1.3 on 2021-08-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210829_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaactual',
            old_name='estudiante',
            new_name='asignacion',
        ),
    ]
