# Generated by Django 3.1.3 on 2021-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210829_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaactual',
            name='nivel',
            field=models.CharField(blank=True, choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5'), ('6', 'Nivel 6'), ('7', 'Nivel 7')], max_length=1, null=True, verbose_name='Nivel a matricular'),
        ),
    ]
