# Generated by Django 3.1.3 on 2021-08-30 02:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210829_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talento_humano',
            name='HojaVida',
            field=models.FileField(upload_to=app.models.HojaDeVida),
        ),
    ]
