# Generated by Django 3.1.3 on 2021-08-30 17:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210829_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talento_humano',
            name='Antecedentes',
            field=models.FileField(upload_to=app.models.CertificadoAntecedentes),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='CarnetDiscap',
            field=models.FileField(upload_to=app.models.CarnetDiscapacidad),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='CertiBancaria',
            field=models.FileField(upload_to=app.models.CertificacionBancaria),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='CertiImpedimento',
            field=models.FileField(upload_to=app.models.CertificadoNoImpedimento),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='CopiaRuc',
            field=models.FileField(upload_to=app.models.Ruc),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='Cursos',
            field=models.FileField(upload_to=app.models.CertificadosCapacitacion),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='Experiencia',
            field=models.FileField(upload_to=app.models.ExperienciaLaboral),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='Historial',
            field=models.FileField(upload_to=app.models.HistorialLaboral),
        ),
        migrations.AlterField(
            model_name='talento_humano',
            name='Titulos',
            field=models.FileField(upload_to=app.models.TitulosAcreditados),
        ),
    ]
