# Generated by Django 3.1.3 on 2021-09-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210830_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='parcial',
            field=models.CharField(choices=[('1', 'Uno')], default=1, max_length=1, null=True, verbose_name='Parcial'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial2',
            field=models.CharField(choices=[('1', 'Dos')], default=1, max_length=1, null=True, verbose_name='Parcial'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='parcial3',
            field=models.CharField(blank=True, choices=[('1', 'Tres')], default=1, max_length=1, null=True, verbose_name='Parcial'),
        ),
    ]
