# Generated by Django 3.1.3 on 2021-09-01 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210831_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='t_nota3',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
