# Generated by Django 3.1.3 on 2021-09-01 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210831_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='t_nota3',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='examen'),
        ),
    ]
