# Generated by Django 3.1.3 on 2021-09-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210831_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaactual',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='matriculaactual',
            name='inicio',
        ),
    ]
