# Generated by Django 3.1.3 on 2021-09-13 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210912_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaactual',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.numero'),
            preserve_default=False,
        ),
    ]
