# Generated by Django 3.1.3 on 2022-01-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20211216_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante',
            old_name='nivel',
            new_name='nivel_comp',
        ),
    ]
