# Generated by Django 3.1.3 on 2022-01-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20220106_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='file_comp',
            field=models.FileField(null=True, upload_to='files/comprobante', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='id_est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='nivel_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.numero', verbose_name='Nivel'),
        ),
    ]
