# Generated by Django 3.1.3 on 2022-01-19 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20220118_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='nivel_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.numero', verbose_name='Nivel'),
        ),
    ]
