# Generated by Django 3.1.3 on 2022-01-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20220118_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_salud',
            name='NomEnfer_fichsa',
            field=models.CharField(max_length=11, verbose_name='Nombre de Enfermedad'),
        ),
    ]
