# Generated by Django 3.1.3 on 2022-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20220128_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosConstantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.PositiveIntegerField()),
                ('fin', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=3)),
            ],
        ),
    ]
