# Generated by Django 3.1.3 on 2022-02-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_parametrosconstantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='programaID',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
