# Generated by Django 3.1.3 on 2021-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210804_2200'),
        ('User', '0003_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ManyToManyField(blank=True, to='app.Cursos'),
        ),
    ]
