# Generated by Django 3.1.3 on 2021-08-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_usuario_programa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Programa',
            new_name='programa',
        ),
    ]
