# Generated by Django 3.1.3 on 2021-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210818_2038'),
        ('User', '0006_auto_20210812_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.ManyToManyField(blank=True, to='app.Cursos', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='programa',
            field=models.ManyToManyField(blank=True, to='app.Programa', verbose_name=' '),
        ),
    ]
