# Generated by Django 3.1.3 on 2021-09-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210831_2223'),
        ('User', '0008_auto_20210906_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asignacionEstudiantes',
            field=models.ManyToManyField(blank=True, to='app.Estudiante', verbose_name=' '),
        ),
    ]
