# Generated by Django 3.1.3 on 2021-09-11 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210831_2223'),
        ('User', '0010_auto_20210910_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='niveles',
        ),
        migrations.CreateModel(
            name='ProgramaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveles', models.ManyToManyField(to='app.Numero')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.programageneral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsigacionParalelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiantes', models.ManyToManyField(to='app.Estudiante')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.paralelo')),
            ],
        ),
    ]
