# Generated by Django 3.1.3 on 2021-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210910_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='asigacionparalelo',
            name='nombre',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
