# Generated by Django 3.1.3 on 2021-09-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210831_2223'),
        ('User', '0012_asigacionparalelo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programageneral',
            name='niveles',
        ),
        migrations.CreateModel(
            name='NivelesGenerales',
            fields=[
                ('niveles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.numero')),
                ('programa_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.programageneral')),
            ],
        ),
    ]
