# Generated by Django 3.1.3 on 2021-09-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20210912_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralelo',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.nivelesgenerales'),
            preserve_default=False,
        ),
    ]
