# Generated by Django 3.1.3 on 2021-09-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20210912_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigacionparalelo',
            name='nombre',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
