# Generated by Django 3.1.3 on 2021-09-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_auto_20210912_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigacionparalelo',
            name='nombre',
            field=models.CharField(max_length=1, verbose_name='Nombre del paralelo'),
        ),
    ]
