# Generated by Django 3.1.3 on 2021-11-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20211111_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacioncursoestudiante',
            old_name='estudiantesCurso',
            new_name='estudiantes',
        ),
    ]
