# Generated by Django 3.1.3 on 2021-11-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_matricula_nivel'),
        ('User', '0022_auto_20211111_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asigacionparalelo',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='asigacionparalelo',
            name='asignacionEstudiantes',
            field=models.ManyToManyField(to='app.MatriculaActual'),
        ),
    ]
