# Generated by Django 3.1.3 on 2022-01-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20211122_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacioncursoestudiante',
            old_name='estudiantes',
            new_name='estudiantes_curso',
        ),
    ]
