# Generated by Django 3.1.3 on 2022-01-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_auto_20220128_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paralelo',
            old_name='nivel',
            new_name='nivel_Paralelo',
        ),
    ]
